-- MySQL Script generated by MySQL Workbench
-- Mon May 27 21:55:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(191) NULL,
  `prenom` VARCHAR(191) NULL,
  `description` LONGTEXT NULL,
  `cv` TEXT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(45) NULL,
  `photo` VARCHAR(145) NULL,
  `prof` BOOLEAN NULL,
  `etudiant` BOOLEAN NULL,
  `admin` BOOLEAN NULL,
  PRIMARY KEY (`id_utilisateur`)
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formation` (
  `id_formation` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `nom_formation` VARCHAR(45) NULL,
  `institution` VARCHAR(45) NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  PRIMARY KEY (`id_formation`),
  CONSTRAINT `fk_formation_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projet` (
  `id_projet` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `titre` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  PRIMARY KEY (`id_projet`),
  CONSTRAINT `fk_projet_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ami`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ami` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ami` (
  `id_ami` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur1` INT NULL,
  `id_utilisateur2` INT NULL,
  `relation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ami`),
  CONSTRAINT `fk_ami_utilisateur1`
    FOREIGN KEY (`id_utilisateur1`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ami_utilisateur2`
    FOREIGN KEY (`id_utilisateur2`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notifications` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notifications` (
  `id_notification` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `type` ENUM('conférence', 'bourse', 'emploi') NULL,
  `titre` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id_notification`),
  CONSTRAINT `fk_notifications_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chatroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chatroom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chatroom` (
  `id_chatroom` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_chatroom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `id_chatroom` INT NULL,
  `id_utilisateur` INT NULL,
  `contenu` TEXT NULL,
  `envoi` DATETIME NULL,
  PRIMARY KEY (`id_message`),
  CONSTRAINT `fk_message_chatroom`
    FOREIGN KEY (`id_chatroom`)
    REFERENCES `mydb`.`chatroom` (`id_chatroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emploi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`emploi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`emploi` (
  `id_emploi` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `entreprise` VARCHAR(45) NULL,
  `lieu` VARCHAR(45) NULL,
  `publication_date` DATETIME NULL,
  `type_contrat` ENUM('CDI', 'CDD', 'stage', 'apprentissage') NULL,
  PRIMARY KEY (`id_emploi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`candidature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`candidature` (
  `id_candidature` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NULL,
  `id_emploi` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id_candidature`),
  CONSTRAINT `fk_candidature_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_emploi`
    FOREIGN KEY (`id_emploi`)
    REFERENCES `mydb`.`emploi` (`id_emploi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
